package learning

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const skillRelPath = ".claude/skills/squad-learnings.md"

func RegenerateSkill(repoRoot string) error {
	all, err := Walk(repoRoot)
	if err != nil {
		return err
	}
	var approved []Learning
	for _, l := range all {
		if l.State == StateApproved {
			approved = append(approved, l)
		}
	}
	dst := filepath.Join(repoRoot, skillRelPath)
	if len(approved) == 0 {
		if err := os.Remove(dst); err != nil && !os.IsNotExist(err) {
			return err
		}
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	tmp := dst + ".tmp"
	if err := os.WriteFile(tmp, []byte(renderSkill(approved)), 0o644); err != nil {
		return err
	}
	if err := os.Rename(tmp, dst); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}

func renderSkill(ls []Learning) string {
	pathSet := map[string]struct{}{}
	for _, l := range ls {
		for _, p := range l.Paths {
			pathSet[p] = struct{}{}
		}
	}
	var paths []string
	for p := range pathSet {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	sort.Slice(ls, func(i, j int) bool {
		if ls[i].Area != ls[j].Area {
			return ls[i].Area < ls[j].Area
		}
		return ls[i].Slug < ls[j].Slug
	})

	var sb strings.Builder
	sb.WriteString("---\nname: squad-learnings\n")
	sb.WriteString("description: Project-specific gotchas, patterns, and dead-ends approved by humans. Auto-loaded for files matching the listed paths. Generated by `squad learning approve` — do not edit by hand.\n")
	sb.WriteString("paths:\n")
	for _, p := range paths {
		fmt.Fprintf(&sb, "  - %s\n", p)
	}
	sb.WriteString("---\n\n# Squad learnings (this repo)\n\n")
	sb.WriteString("Human-approved learnings derived from prior sessions. Loaded automatically when you open files matching the `paths:` above. Read them before changing code in those areas — this is how the team avoids repeat mistakes.\n\n")
	sb.WriteString("If a learning here disagrees with what you observe, treat the disagreement as data: open the learning file, append a note, and propose an updated learning at session end. Do not silently ignore.\n\n")

	groups := map[string][]Learning{}
	var areas []string
	seen := map[string]bool{}
	for _, l := range ls {
		if !seen[l.Area] {
			seen[l.Area] = true
			areas = append(areas, l.Area)
		}
		groups[l.Area] = append(groups[l.Area], l)
	}
	sort.Strings(areas)
	for _, area := range areas {
		fmt.Fprintf(&sb, "## %s\n\n", area)
		for _, l := range groups[area] {
			fmt.Fprintf(&sb, "### %s — %s (%s)\n\nRead: `%s`\n\n", l.Slug, l.Title, l.Kind, l.Path)
		}
	}
	return sb.String()
}
