package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/spf13/cobra"

	"github.com/zsiec/squad/internal/learning"
)

var diffFenceRe = regexp.MustCompile("(?s)```diff\\n(.*?)```")

var (
	ErrProposalNotFound = errors.New("agents-md proposal not found")
	ErrApplyFailed      = errors.New("git apply failed")
)

// ApplyFailedError carries the git apply stderr so the cobra wrapper can
// echo it to the user; MCP callers can read .Stderr directly.
type ApplyFailedError struct {
	Stderr string
	Err    error
}

func (e *ApplyFailedError) Error() string {
	return fmt.Sprintf("%s: %s", ErrApplyFailed.Error(), strings.TrimSpace(e.Stderr))
}

func (e *ApplyFailedError) Is(target error) bool { return target == ErrApplyFailed }
func (e *ApplyFailedError) Unwrap() error        { return e.Err }

type LearningAgentsMdApproveArgs struct {
	RepoRoot string `json:"repo_root"`
	ID       string `json:"id"`
}

type LearningAgentsMdApproveResult struct {
	AppliedPath string `json:"applied_path"`
	Branch      string `json:"branch"`
	// PRURL is empty when the repo has no remote or `gh` is unavailable —
	// in that case the commit lives on Branch locally and the operator can
	// finish the flow by hand. PRSkippedReason explains why.
	PRURL           string `json:"pr_url,omitempty"`
	PRSkippedReason string `json:"pr_skipped_reason,omitempty"`
}

func LearningAgentsMdApprove(ctx context.Context, args LearningAgentsMdApproveArgs) (*LearningAgentsMdApproveResult, error) {
	proposed := filepath.Join(args.RepoRoot, ".squad", "learnings", "agents-md", "proposed", args.ID+".md")
	body, err := os.ReadFile(proposed)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("%w: %s", ErrProposalNotFound, proposed)
		}
		return nil, fmt.Errorf("read proposal: %w", err)
	}
	diff := extractDiff(body)
	if diff == "" {
		return nil, fmt.Errorf("no diff fence found in proposal %s", proposed)
	}

	origBranch, err := gitCurrentBranch(args.RepoRoot)
	if err != nil {
		return nil, err
	}
	branch := "squad/learning-agents-md-" + args.ID
	if err := gitCheckoutNewBranch(args.RepoRoot, branch); err != nil {
		return nil, err
	}

	// From here on, any failure must restore the original branch before
	// surfacing the error so the operator's working tree isn't stranded
	// on an in-progress squad branch. The hard reset clears any partial
	// `git apply` so the subsequent checkout never trips on a dirty tree.
	restore := func(failure error) error {
		_, _ = runGit(args.RepoRoot, "reset", "--hard", "HEAD")
		_ = gitCheckout(args.RepoRoot, origBranch)
		_ = gitDeleteBranch(args.RepoRoot, branch)
		return failure
	}

	if err := gitApply(args.RepoRoot, diff); err != nil {
		return nil, restore(err)
	}
	if err := gitAddCommit(args.RepoRoot, "AGENTS.md",
		"docs(agents-md): apply learning "+args.ID); err != nil {
		return nil, restore(err)
	}

	res := &LearningAgentsMdApproveResult{Branch: branch}
	switch reason := pushAndOpenPR(ctx, args.RepoRoot, branch, args.ID, res); {
	case reason == "":
		// PR opened successfully.
	default:
		res.PRSkippedReason = reason
	}

	if err := gitCheckout(args.RepoRoot, origBranch); err != nil {
		return nil, fmt.Errorf("agents-md approve: checkout %s: %w (squad branch %s left in place)", origBranch, err, branch)
	}

	applied := filepath.Join(args.RepoRoot, ".squad", "learnings", "agents-md", "applied", args.ID+".md")
	if err := os.MkdirAll(filepath.Dir(applied), 0o755); err != nil {
		return nil, err
	}
	if err := os.WriteFile(applied, learning.RewriteState(body, learning.State("applied")), 0o644); err != nil {
		return nil, err
	}
	if err := os.Remove(proposed); err != nil {
		return nil, err
	}
	res.AppliedPath = applied
	return res, nil
}

// pushAndOpenPR best-effort pushes branch and opens a PR. Returns "" on
// success or a short reason when the PR step was skipped (no remote, no
// gh binary, push failed). The squad branch remains either way so the
// operator can pick up the flow by hand.
func pushAndOpenPR(ctx context.Context, repoRoot, branch, id string, res *LearningAgentsMdApproveResult) string {
	if !gitHasRemote(repoRoot) {
		return "no remote configured"
	}
	if _, err := exec.LookPath("gh"); err != nil {
		return "gh CLI not found in PATH"
	}
	if err := gitPush(ctx, repoRoot, branch); err != nil {
		return fmt.Sprintf("git push failed: %s", err)
	}
	url, err := ghCreatePR(ctx, repoRoot, branch,
		"docs(agents-md): apply learning "+id,
		"Auto-generated by `squad learning agents-md-approve`. Source: `.squad/learnings/agents-md/applied/"+id+".md`.")
	if err != nil {
		return fmt.Sprintf("gh pr create failed: %s", err)
	}
	res.PRURL = url
	return ""
}

func gitCurrentBranch(repoRoot string) (string, error) {
	out, err := runGit(repoRoot, "rev-parse", "--abbrev-ref", "HEAD")
	if err != nil {
		return "", fmt.Errorf("git rev-parse HEAD: %w", err)
	}
	return strings.TrimSpace(out), nil
}

func gitCheckoutNewBranch(repoRoot, branch string) error {
	// `-B` resets the branch to current HEAD if it already exists. Re-running
	// approve on the same id (e.g., after a manual revert) shouldn't fail
	// with an opaque exit-128.
	if _, err := runGit(repoRoot, "checkout", "-B", branch); err != nil {
		return fmt.Errorf("git checkout -B %s: %w", branch, err)
	}
	return nil
}

func gitCheckout(repoRoot, branch string) error {
	if _, err := runGit(repoRoot, "checkout", branch); err != nil {
		return fmt.Errorf("git checkout %s: %w", branch, err)
	}
	return nil
}

func gitDeleteBranch(repoRoot, branch string) error {
	if _, err := runGit(repoRoot, "branch", "-D", branch); err != nil {
		return fmt.Errorf("git branch -D %s: %w", branch, err)
	}
	return nil
}

func gitAddCommit(repoRoot, path, message string) error {
	if _, err := runGit(repoRoot, "add", path); err != nil {
		return fmt.Errorf("git add %s: %w", path, err)
	}
	if _, err := runGit(repoRoot, "commit", "-m", message); err != nil {
		return fmt.Errorf("git commit: %w", err)
	}
	return nil
}

func gitHasRemote(repoRoot string) bool {
	// Specifically probe `origin` since gitPush hardcodes it. Other remotes
	// passing a generic check would still fail at push time with a less
	// useful error.
	out, err := runGit(repoRoot, "remote", "get-url", "origin")
	if err != nil {
		return false
	}
	return strings.TrimSpace(out) != ""
}

func gitPush(ctx context.Context, repoRoot, branch string) error {
	c := exec.CommandContext(ctx, "git", "push", "-u", "origin", branch)
	c.Dir = repoRoot
	var errBuf bytes.Buffer
	c.Stderr = &errBuf
	if err := c.Run(); err != nil {
		return fmt.Errorf("%w: %s", err, strings.TrimSpace(errBuf.String()))
	}
	return nil
}

func ghCreatePR(ctx context.Context, repoRoot, branch, title, body string) (string, error) {
	c := exec.CommandContext(ctx, "gh", "pr", "create",
		"--head", branch, "--title", title, "--body", body)
	c.Dir = repoRoot
	out, err := c.Output()
	if err != nil {
		var stderr string
		if exErr, ok := err.(*exec.ExitError); ok {
			stderr = strings.TrimSpace(string(exErr.Stderr))
		}
		return "", fmt.Errorf("%w: %s", err, stderr)
	}
	return strings.TrimSpace(string(out)), nil
}

// runGit runs git in repoRoot. When the repo has no committer identity
// configured (CI / fresh checkout), a synthetic squad identity is injected
// so commits don't fail; otherwise the operator's real user.name /
// user.email is preserved so the resulting PR carries their authorship.
func runGit(repoRoot string, args ...string) (string, error) {
	c := exec.Command("git", args...)
	c.Dir = repoRoot
	c.Env = os.Environ()
	if !gitHasCommitterIdentity(repoRoot) {
		c.Env = append(c.Env,
			"GIT_AUTHOR_NAME=squad", "GIT_AUTHOR_EMAIL=squad@local",
			"GIT_COMMITTER_NAME=squad", "GIT_COMMITTER_EMAIL=squad@local")
	}
	out, err := c.Output()
	return string(out), err
}

func gitHasCommitterIdentity(repoRoot string) bool {
	c := exec.Command("git", "config", "user.email")
	c.Dir = repoRoot
	out, err := c.Output()
	if err != nil {
		return false
	}
	return strings.TrimSpace(string(out)) != ""
}

func newLearningAgentsMdApproveCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "agents-md-approve <id>",
		Short: "Apply a proposed AGENTS.md diff via `git apply`; on success, archive the proposal",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			root, err := discoverRepoRoot()
			if err != nil {
				return err
			}
			res, err := LearningAgentsMdApprove(cmd.Context(), LearningAgentsMdApproveArgs{
				RepoRoot: root, ID: args[0],
			})
			if err != nil {
				var af *ApplyFailedError
				if errors.As(err, &af) {
					_, _ = cmd.ErrOrStderr().Write([]byte(af.Stderr))
					return fmt.Errorf("git apply: %w", af.Err)
				}
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "branch: %s\n", res.Branch)
			if res.PRURL != "" {
				fmt.Fprintf(cmd.OutOrStdout(), "pr: %s\n", res.PRURL)
			} else if res.PRSkippedReason != "" {
				fmt.Fprintf(cmd.OutOrStdout(), "PR skipped (%s) — push and open the PR by hand from %s\n",
					res.PRSkippedReason, res.Branch)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "applied: %s\n", res.AppliedPath)
			return nil
		},
	}
}

func extractDiff(body []byte) string {
	m := diffFenceRe.FindSubmatch(body)
	if m == nil {
		return ""
	}
	return string(m[1])
}

func gitApply(repoRoot, diff string) error {
	c := exec.Command("git", "apply", "--whitespace=nowarn", "-")
	c.Dir = repoRoot
	c.Stdin = strings.NewReader(diff)
	var errBuf bytes.Buffer
	c.Stderr = &errBuf
	if err := c.Run(); err != nil {
		return &ApplyFailedError{Stderr: errBuf.String(), Err: err}
	}
	return nil
}
