package main

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/spf13/cobra"

	"github.com/zsiec/squad/internal/retro"
)

type RetroArgs struct {
	DB       *sql.DB `json:"-"`
	RepoID   string  `json:"repo_id"`
	RepoRoot string  `json:"repo_root"`
	Week     string  `json:"week,omitempty"`
	MinItems int     `json:"min_items,omitempty"`
	Now      time.Time
}

type RetroResult struct {
	Path       string `json:"path"`
	Period     string `json:"period"`
	Wrote      bool   `json:"wrote"`
	Sufficient bool   `json:"sufficient"`
}

func RunRetro(ctx context.Context, args RetroArgs) (*RetroResult, error) {
	now := args.Now
	if now.IsZero() {
		now = time.Now()
	}
	var period retro.Period
	if args.Week == "" {
		period = retro.CurrentWeek(now)
	} else {
		p, err := retro.ParseWeek(args.Week)
		if err != nil {
			return nil, err
		}
		period = p
	}
	body, ok, err := retro.Generate(ctx, args.DB, retro.Opts{
		RepoID:   args.RepoID,
		Period:   period,
		MinItems: args.MinItems,
	})
	if err != nil {
		return nil, err
	}
	dir := filepath.Join(args.RepoRoot, ".squad", "retros")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	out := filepath.Join(dir, period.String()+".md")
	tmp := out + ".tmp"
	if err := os.WriteFile(tmp, []byte(body), 0o644); err != nil {
		return nil, err
	}
	if err := os.Rename(tmp, out); err != nil {
		_ = os.Remove(tmp)
		return nil, err
	}
	if err := regenerateRetroSkill(args.RepoRoot); err != nil {
		return nil, fmt.Errorf("regenerate retro skill: %w", err)
	}
	return &RetroResult{
		Path:       out,
		Period:     period.String(),
		Wrote:      true,
		Sufficient: ok,
	}, nil
}

func newRetroCmd() *cobra.Command {
	var week string
	var minItems int
	cmd := &cobra.Command{
		Use:   "retro",
		Short: "Generate the weekly retro digest at .squad/retros/YYYY-WNN.md",
		Long: "Reads the last 7 days from the global ledger and writes a deterministic markdown digest:\n" +
			"top failure modes, slowest item type, and one rule-based process recommendation. Pass\n" +
			"--week YYYY-WNN to regenerate a specific past week (idempotent overwrite).",
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := cmd.Context()
			bc, err := bootClaimContext(ctx)
			if err != nil {
				return err
			}
			defer bc.Close()
			repoRoot, err := discoverRepoRoot()
			if err != nil {
				return err
			}
			res, err := RunRetro(ctx, RetroArgs{
				DB: bc.db, RepoID: bc.repoID, RepoRoot: repoRoot,
				Week: week, MinItems: minItems,
			})
			if err != nil {
				return err
			}
			suffix := "ok"
			if !res.Sufficient {
				suffix = "insufficient signal"
			}
			fmt.Fprintf(cmd.OutOrStdout(), "wrote %s (%s)\n", res.Path, suffix)
			return nil
		},
	}
	cmd.Flags().StringVar(&week, "week", "", "ISO week (YYYY-WNN); default: this week")
	cmd.Flags().IntVar(&minItems, "min-items", 0, "minimum closed items to render a real retro (default 5)")
	return cmd
}

const retroSkillRel = ".claude/skills/squad-retros.md"

// regenerateRetroSkill rewrites the auto-load skill stub to point at
// the most recent retro file under .squad/retros/. It is callable
// safely when the directory has zero files (the stub is removed).
func regenerateRetroSkill(repoRoot string) error {
	retroDir := filepath.Join(repoRoot, ".squad", "retros")
	entries, err := os.ReadDir(retroDir)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	var newest string
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || filepath.Ext(name) != ".md" {
			continue
		}
		if name > newest {
			newest = name
		}
	}
	dst := filepath.Join(repoRoot, retroSkillRel)
	if newest == "" {
		if err := os.Remove(dst); err != nil && !os.IsNotExist(err) {
			return err
		}
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	body := renderRetroSkill(newest)
	tmp := dst + ".tmp"
	if err := os.WriteFile(tmp, []byte(body), 0o644); err != nil {
		return err
	}
	if err := os.Rename(tmp, dst); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}

func renderRetroSkill(filename string) string {
	return "---\nname: squad-retros\n" +
		"description: Most recent weekly retro generated by `squad retro`. Surfaces failure modes and process suggestions from the prior week — read before picking up new work.\n" +
		"paths:\n" +
		"  - \"AGENTS.md\"\n" +
		"  - \"CLAUDE.md\"\n" +
		"  - \".squad/**\"\n" +
		"---\n\n" +
		"# Squad retro (most recent)\n\n" +
		"The newest weekly retro lives at `.squad/retros/" + filename + "`. Read it before claiming work — process recommendations there reflect real signal from the prior week's ledger.\n"
}
