package hygiene

import (
	"context"
	"database/sql"
	"fmt"
	"sort"
	"strings"
	"time"
)

type StatusItem struct {
	ID, Title, Priority, Status, Estimate string
}

func DumpStatus(ctx context.Context, db *sql.DB, repoID string, items []StatusItem, clock func() time.Time) (string, error) {
	rows, err := db.QueryContext(ctx, `
		SELECT item_id, agent_id, COALESCE(intent, ''), claimed_at
		FROM claims WHERE repo_id = ? ORDER BY claimed_at, item_id`, repoID)
	if err != nil {
		return "", err
	}
	defer rows.Close()
	type cl struct {
		ID, Agent, Intent string
		TS                int64
	}
	var claims []cl
	claimed := map[string]bool{}
	for rows.Next() {
		var c cl
		if err := rows.Scan(&c.ID, &c.Agent, &c.Intent, &c.TS); err != nil {
			return "", err
		}
		claims = append(claims, c)
		claimed[c.ID] = true
	}
	ready := map[string][]StatusItem{}
	var blocked []StatusItem
	for _, it := range items {
		if claimed[it.ID] || it.Status == "done" {
			continue
		}
		if it.Status == "blocked" {
			blocked = append(blocked, it)
			continue
		}
		ready[it.Priority] = append(ready[it.Priority], it)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Status Board\n\n*Auto-generated by squad dump-status at %s*\n\n",
		clock().Format("2006-01-02 15:04 UTC"))
	fmt.Fprintln(&b, "## In Progress")
	if len(claims) == 0 {
		fmt.Fprintln(&b, "*nothing in progress*")
	}
	for _, c := range claims {
		fmt.Fprintf(&b, "- %s (%s): %s\n", c.ID, c.Agent, c.Intent)
	}
	fmt.Fprintln(&b)
	for _, p := range []string{"P0", "P1", "P2", "P3"} {
		list := ready[p]
		if len(list) == 0 {
			continue
		}
		sort.Slice(list, func(i, j int) bool { return list[i].ID < list[j].ID })
		fmt.Fprintf(&b, "## Ready — %s\n", p)
		for _, it := range list {
			fmt.Fprintf(&b, "- %s  %s  (%s)\n", it.ID, it.Title, it.Estimate)
		}
		fmt.Fprintln(&b)
	}
	if len(blocked) > 0 {
		sort.Slice(blocked, func(i, j int) bool { return blocked[i].ID < blocked[j].ID })
		fmt.Fprintln(&b, "## Blocked")
		for _, it := range blocked {
			fmt.Fprintf(&b, "- %s  %s\n", it.ID, it.Title)
		}
	}
	return b.String(), nil
}
