package scaffold

import (
	"fmt"
	"sort"
	"strings"

	"github.com/zsiec/squad/internal/epics"
	"github.com/zsiec/squad/internal/items"
	"github.com/zsiec/squad/internal/specs"
)

// RenderDocIndex turns a ledger snapshot into the two index pages
// `docs/specs.md` and `docs/epics.md`. Pure function — given identical
// inputs, returns identical strings (byte-stable). Sort order is
// alphabetical by Name so re-renders stay deterministic regardless of
// filesystem walk order.
//
// Spec status is derived from child epics: a spec whose every linked
// epic has status=done is rendered as done; otherwise active. Specs
// have no Status field of their own. Epic status maps "open"→"active";
// any other value renders verbatim.
func RenderDocIndex(specsList []specs.Spec, epicsList []epics.Epic, itemsList []items.Item) (specsMD, epicsMD string) {
	itemsByEpic := map[string]int{}
	for _, it := range itemsList {
		if it.Epic != "" {
			itemsByEpic[it.Epic]++
		}
	}

	epicsBySpec := map[string][]epics.Epic{}
	for _, e := range epicsList {
		epicsBySpec[e.Spec] = append(epicsBySpec[e.Spec], e)
	}

	sortedSpecs := append([]specs.Spec(nil), specsList...)
	sort.Slice(sortedSpecs, func(i, j int) bool { return sortedSpecs[i].Name < sortedSpecs[j].Name })
	sortedEpics := append([]epics.Epic(nil), epicsList...)
	sort.Slice(sortedEpics, func(i, j int) bool { return sortedEpics[i].Name < sortedEpics[j].Name })

	var sb strings.Builder
	sb.WriteString("# Specs\n\n")
	sb.WriteString("Generated by `squad scaffold doc-index` from current ledger state.\n\n")
	if len(sortedSpecs) == 0 {
		sb.WriteString("_No specs._\n")
	}
	for _, s := range sortedSpecs {
		title := s.Title
		if title == "" {
			title = s.Name
		}
		fmt.Fprintf(&sb, "- [%s](../.squad/specs/%s.md) — %s\n",
			title, s.Name, deriveSpecStatus(epicsBySpec[s.Name]))
	}
	specsMD = sb.String()

	sb.Reset()
	sb.WriteString("# Epics\n\n")
	sb.WriteString("Generated by `squad scaffold doc-index` from current ledger state.\n\n")
	if len(sortedEpics) == 0 {
		sb.WriteString("_No epics._\n")
	}
	for _, e := range sortedEpics {
		fmt.Fprintf(&sb, "- [%s](../.squad/epics/%s.md) — %s · %s\n",
			e.Name, e.Name, mapEpicStatus(e.Status), itemCountLabel(itemsByEpic[e.Name]))
	}
	epicsMD = sb.String()
	return
}

func deriveSpecStatus(children []epics.Epic) string {
	if len(children) == 0 {
		return "active"
	}
	for _, e := range children {
		if e.Status != "done" {
			return "active"
		}
	}
	return "done"
}

func mapEpicStatus(s string) string {
	if s == "open" || s == "" {
		return "active"
	}
	return s
}

func itemCountLabel(n int) string {
	if n == 1 {
		return "1 item"
	}
	return fmt.Sprintf("%d items", n)
}
